enable_audio_bell no
include dracula.conf
include Solarized_Light.conf

font_size 9.0

# cursor_trail 3
# cursor_trail_decay 0.2 0.3


# BEGIN_KITTY_THEME
# Catppuccin-Frappe
include current-theme.conf
# END_KITTY_THEME
