unbind C-b
set -g prefix C-a
#set -g prefix2 C-w
bind C-a send-prefix
#bind C-w send-prefix -2


set -g mouse on


#### copy mode : vim ####

# set vi mode for copy mode
setw -g mode-keys vi

# copy mode using 'Esc'
#unbind [
#bind Escape copy-mode
#set -sg escape-time 5

# More friendly split pane
bind-key H split-window -h
bind-key V split-window -v

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r M-h resize-pane -L 5
bind -r M-l resize-pane -R 5
bind -r M-j resize-pane -D 5
bind -r M-k resize-pane -U 5

bind -r C-n next-window
bind -r C-p previous-window

#bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy && wl-paste -n | wl-copy -p"
#bind-key p run "wl-paste -n | tmux load-buffer - ; tmux paste-buffer"

if-shell '[ -n "$WAYLAND_DISPLAY" ]' {
    bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy && wl-paste -n | wl-copy -p"
    bind-key p run "wl-paste -n | tmux load-buffer - ; tmux paste-buffer"
} {
    bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -i -sel clip > /dev/null"
    bind-key p run "xclip -o -sel clip | tmux load-buffer - ; tmux paste-buffer"
}

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

set-option -g @apply-session-color '
  name="$(tmux display-message -p "#{session_name}")"
  hash=$(printf "%s" "$name" | cksum | cut -d" " -f1)
  color=$(( (hash % 200) + 16 ))


  # Apply to tmux
  tmux set-option -gq status-bg "colour${color}"
  tmux set-option -g status-fg black
'

run-shell "#{@apply-session-color}"
set-hook -g client-session-changed "run-shell \"#{@apply-session-color}\""
set-hook -g session-renamed        "run-shell \"#{@apply-session-color}\""
set-hook -g session-created        "run-shell \"#{@apply-session-color}\""


# POPUP WINDOWS
# These two shortcuts provide popup windows in tmux. The lowercase version
# makes a popup that named uniquely to the working directory. This is great
# for making a popup window in a coding project.
#
# The uppercase version makes a "global" popup window. Great for persisting
# things globally for a long period of time.

bind r source-file ~/.tmux.conf \; display "Reloaded!"

bind-key -n C-g run-shell '\
  current_name="#{session_name}"; \
  tmux display "#{session_name}"; \
  if printf "%s" "$current_name" | grep -qi "^popup-"; then \
    tmux detach-client; \
  else \
    popup_name="popup-${current_name}"; \
    tmux display-popup -d "#{pane_current_path}" -xC -yC -w 80% -h 75% \
      -E "tmux attach-session -t \"$popup_name\" || tmux new-session -s \"$popup_name\""; \
  fi \
'

bind G run-shell '\
    POPUP_NAME="popup-global"; \
    if [ "#{session_name}" = "$POPUP_NAME" ]; then \
        tmux detach-client; \
    else \
        tmux display-popup -xC -yC -w 80% -h 75% -E "tmux attach-session -t $POPUP_NAME || tmux new-session -s $POPUP_NAME"; \
    fi \
'

run '~/.tmux/plugins/tpm/tpm'
